### ISSUE TITLE
v0.2.4 TODO list

### ISSUE THREAD

**Issue by ASKabalan** [DifferentiableUniverseInitiative/jaxDecomp#37]
v0.2.4

- [x] Fix gradient issue in PFFT3D because of the promote to complex inside the vjp rule fixed https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/49 (was released with v0.2.3 because it was urgent)
- [x] Implement Batching rule https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/56
- [x] Implement JVP  https://github.com/DifferentiableUniverseInitiative/jaxDecomp/pull/56

**Comment by ASKabalan** [comment]
v0.2.5

- [ ] Support rfft and irfft
- [ ] Support rfftfreq
- [ ] update README
